services:
  app:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped