"""empty message

Revision ID: 9f22a5e3fddc
Revises: 8a8c4b9d91c7
Create Date: 2024-05-14 14:48:39.003017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f22a5e3fddc'
down_revision = '8a8c4b9d91c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
