"""empty message

Revision ID: bf766669f7a1
Revises: bf18bef85801
Create Date: 2024-04-29 23:52:50.684377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf766669f7a1'
down_revision = 'bf18bef85801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panier', schema=None) as batch_op:
        batch_op.drop_column('valide')

    # ### end Alembic commands ###
