"""empty message

Revision ID: ffa40810f17a
Revises: 
Create Date: 2024-04-27 15:23:51.445711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa40810f17a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livres', schema=None) as batch_op:
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
